/* 
Modelo relacional
MEDICOS(DNI: Int, NyA: String, Especialidad: String)
    CP: DNI
    CNN: NyA
PACIENTES(DNI: Int, NyA:String)
    CP: DNI
    CNN: NyA
Atiende(DNIMED, DNIPAC)
    CP: DNIMED, DNIPAC
    CF: DNIMED -> MEDICOS(DNI)
        DNIPAC -> PACIENTES(DNI)
ESTUDIOS(idE: Int, fecha: Date, Desc: String, DNIPAC: Int, DNIMED: Int)
    CP: idE
    CF: DNIPAC -> PACIENTES(DNI)
        DNIMED -> MEDICOS(DNI)
    CNN: fecha, DNIPAC, DNIMED
*/
CREATE TABLE MEDICOS(
    DNI INTEGER,
    NyA CHAR(50) NOT NULL,
    Especialidad CHAR(10),
    PRIMARY KEY(DNI)
)
CREATE TABLE PACIENTES(
    DNI INTEGER,
    NyA CHAR(50) NOT NULL
)
CREATE TABLE Atiende(
    DNIMED INTEGER,
    DNIPAC INTEGER,
    PRIMARY KEY(DNIMED, DNIPAC)
)
CREATE TABLE ESTUDIOS(
    idE INTEGER,
    fecha DATE NOT NULL,
    descripcion CHAR(50),
    DNIPAC INTEGER NOT NULL,
    DNIMED INTEGER NOT NULL,
    PRIMARY KEY(idE),
    FOREIGN KEY(DNIMED) REFERENCES MEDICOS(DNI),
    FOREIGN KEY(DNIPAC) REFERENCES PACIENTES(DNI)
)